name: JCA
dependencies:
 - python=3.11.7
 - pip=23.3.1
 - pytorch=2.1.2
 - torchvision=0.16.2
 - torchaudio=2.1.2
 - pytorch-cuda=12.1
 - pip:
     - pypesq==1.2.4
     - opencv-python==4.9.0.80
     - soundfile==0.12.1
     - scipy==1.12.0
     - pystoi==0.4.1
     - thop==0.1.1.post2209072238
     - timm==0.9.12
     - pytorch-lightning==2.1.3
     - torch-optimizer==0.3.0
     - tensorboard==2.15.1
     - pandas==2.2.0
     - sigfig==1.3.3
     - einops==0.7.0